export const SharedContants = {
  role: {
    staffRole: "staff",
    adminRole: "Admin",
  },
  sideNav: {
    StaffSideNav: [
      {
        routerLink: "/checkIn",
        routerLinkText: "Check In",
        icon: "assignment_turned_in",
      },
      {
        routerLink: "/inFlight",
        routerLinkText: "In Flight",
        icon: "assignment",
      },
      { routerLink: "/about", routerLinkText: "About", icon: "info" },
      {
        routerLink: "/logout",
        routerLinkText: "Logout",
        icon: "logout",
      },
    ],
    AdminSideNav: [
      {
        routerLink: "/admin",
        routerLinkText: "Administrator",
        icon: "account_box",
      },
      { routerLink: "/about", routerLinkText: "About", icon: "info" },
      {
        routerLink: "/logout",
        routerLinkText: "Logout",
        icon: "logout",
      },
    ],
  },
  rowSeatName: ["A", "B", "C", "D", "E", "F"],
  monthNames: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
  text: {
    checkedIn: "checked-in",
    notCheckedIn: "not-checked-in",
    wheelChair: "wheel-chair",
    noWheelChair: "no-wheel-chair",
    infants: "infants",
    noInfants: "no-infants",
    mealNotRequired: "Not Required",
    normalVegMeal: "Veg Meal",
    normalNonVegMeal: "Non Veg Meal",
    specialVegMeal: "Special Veg Meal",
    specialNonVegMeal: "Special Non Veg Meal",
  },
  tabel: {
    displayedColumns: {
      checkIn: [
        "name",
        "seatNumber",
        "passportNumber",
        "checkedIn",
        "wheelChair",
        "infants",
        "checkedInServices",
        "edit",
      ],
      inFlight: [
        "name",
        "seatNumber",
        "passportNumber",
        "meal",
        "inFlightServices",
        "shopItem",
        "edit",
      ],
      admin: [
        "name",
        "seatNumber",
        "passportNumber",
        "checkedIn",
        "wheelChair",
        "infants",
        "checkedInServices",
        "meal",
        "inFlightServices",
        "shopItem",
        "edit",
      ],
    },
    filterOptions: {
      checkIn: [
        { value: "none", name: "None" },
        { value: "checkedIn", name: "Checked In" },
        { value: "notCheckedIn", name: "Not Checked In" },
        { value: "wheelChair", name: "Wheel Chair Requried" },
        { value: "infants", name: "With Infants" },
        { value: "checkInServices", name: "Opted Services" },
      ],
      inFlight: [
        { value: "none", name: "None" },
        { value: "notRequried", name: "Meal Not Requried" },
        { value: "vegMeal", name: "Opted Veg Meal" },
        { value: "specialVegMeal", name: "Opted Special Veg Meal" },
        { value: "nonVegMeal", name: "Opted Non-Veg Meal" },
        { value: "specialNonVegMeal", name: "Opted Special Non-Veg Meal" },
        { value: "inFLightServices", name: "Opted Services" },
        { value: "shopItems", name: "Shopped Items" },
      ],
      admin: [
        { value: "none", name: "None" },
        { value: "checkedIn", name: "Checked In" },
        { value: "notCheckedIn", name: "Not Checked In" },
        { value: "wheelChair", name: "Wheel Chair Requried" },
        { value: "infants", name: "With Infants" },
        { value: "checkInServices", name: "Opted Check-In Services" },
        { value: "notRequried", name: "Meal Not Requried" },
        { value: "vegMeal", name: "Opted Veg Meal" },
        { value: "specialVegMeal", name: "Opted Special Veg Meal" },
        { value: "nonVegMeal", name: "Opted Non-Veg Meal" },
        { value: "specialNonVegMeal", name: "Opted Special Non-Veg Meal" },
        { value: "inFLightServices", name: "Opted In-Flight Services" },
        { value: "shopItems", name: "Shopped Items" },
      ],
    },
  },
};
